baseURL = "https://sharec.js.org"
languageCode = "en-us"
title = "Sharec"
author = "lamartire"
theme = "sharec"
pygmentsUseClasses = true
assetDir = "."

[menu]
  [[menu.sidebar]]
    identifier = "intro"
    title = "Introduction"
    url = "/"
    weight = 8

  [[menu.sidebar]]
    identifier = "overview"
    title = "Overview"
    url = "/overview"
    weight = 9

  [[menu.sidebar]]
    identifier = "configuration"
    title = "Configuration"
    url = "/configuration"
    weight = 10
