on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        version: '14.x'
    - uses: bahmutov/npm-install@v1
    - name: Running linters
      run: |
        yarn lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        node_version: ['12.x', '14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        version: ${{ matrix.node_version }}
    - uses: bahmutov/npm-install@v1
    - name: Install packages dependencies
      run: |
        npx lerna bootstrap
    - name: Running tests
      run: |
        npx lerna run test
