on: [push]

jobs:
  lint:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: ['14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Lerna installing
      run: |
        npm install -g lerna
    - name: Install dependencies
      run: |
        yarn
    - name: Running linters
      run: |
        yarn lint

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node_version: ['12.x', '14.x']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Lerna installing
      run: |
        npm install -g lerna
    - name: Install dependencies
      run: |
        yarn
    - name: Install packages dependencies
      run: |
        lerna exec yarn
    - name: Running tests
      run: |
        lerna run test
